# general settings
name: rice2_ATT_CR
model_type: ImageCleanModel
scale: 1
num_gpu: 4
manual_seed: 100

# dataset and data loader settings
datasets:
  train:
    name: TrainSet
    type: Dataset_PairedImage
    dataroot_gt: /data/wy/CV/data/cloud/RICE_DATASET/RICE2/train/target
    dataroot_lq: /data/wy/CV/data/cloud/RICE_DATASET/RICE2/train/input
    geometric_augs: true

    filename_tmpl: '{}'
    io_backend:
      type: disk

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 4

    ### ------- Training on single fixed-patch size 128x128---------
    mini_batch_sizes: [4]
    iters: [37000]
    gt_size: 256
    gt_sizes: [256]
    ### ------------------------------------------------------------

    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: ValSet
    type: Dataset_PairedImage
    dataroot_gt: /data/wy/CV/data/cloud/RICE_DATASET/RICE2/test/target
    dataroot_lq: /data/wy/CV/data/cloud/RICE_DATASET/RICE2/test/input
    gt_size: 256
    io_backend:
      type: disk

# network structures
network_g:
  type: ATT_CR
  inp_channels: 3
  out_channels: 3
  dim: 48
  num_blocks: [1, 2, 8, 2, 1] #[4,6,6,8]
  num_refinement_blocks: 2 #4
  heads: [2,2,8,2,2]
  scales: [[3,5], [1,3,], [1,3], [1,3,], [3,5]] #
  ffn_expansion_factor: 2.66
  bias: False
  LayerNorm_type: WithBias
 
  

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  total_iter: 37000
  warmup_iter: -1 # no warm up
  use_grad_clip: true

  # Split 300k iterations into two cycles. 
  # 1st cycle: fixed 3e-4 LR for 92k iters. 
  # 2nd cycle: cosine annealing (3e-4 to 1e-6) for 208k iters.
  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [11100, 25900]
    restart_weights: [1,1]
    eta_mins: [0.0004,0.000002]   
  
  mixing_augs:
    mixup: false
    mixup_beta: 1.2
    use_identity: true

  optim_g:
    type: AdamW
    lr: !!float 4e-4
    weight_decay: !!float 1e-4
    betas: [0.9, 0.999]
  
  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  window_size: 8
  val_freq: !!float 1e3
  save_img: false
  rgb2bgr: true
  use_image: true
  max_minibatch: 4

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 1e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
